from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, ToolMessage

from tools.sql_tool import sql_tool
from context.app_context import ApplicationContext

from services.sql_service import run_sql_workflow
from memory.memory_service import get_memory_context

from dotenv import load_dotenv


# ============================================================
# Environment
# ============================================================

load_dotenv()


# ============================================================
# LLM
# ============================================================

llm = ChatOpenAI(
    model="gpt-4.1-mini",
    temperature=0
)


# ============================================================
# Bind tools to the LLM
# ============================================================

llm_with_tools = llm.bind_tools([
    sql_tool
])


# ============================================================
# Tool Registry
# ============================================================
#
# This registry is used by Python to identify
# the actual LangChain tool requested by the LLM.
#
# Example:
#
# LLM says:
#     "sql_tool"
#
# Python finds:
#     TOOLS["sql_tool"]
# ============================================================

TOOLS = {
    "sql_tool": sql_tool
}


# ============================================================
# SQL Tool Runtime Executor
# ============================================================
#
# The LLM provides:
#
#     question
#
# The application provides:
#
#     app_context
#         ├── current_user
#         └── db_pool
#
# ============================================================

async def execute_sql_tool(
    tool_args: dict,
    app_context: ApplicationContext
):

    # --------------------------------------------------------
    # Get the question generated by the LLM
    # --------------------------------------------------------

    question = tool_args["question"]


    # --------------------------------------------------------
    # Load database schema
    # --------------------------------------------------------

    with open("schema.txt", "r") as f:
        schema = f.read()


    # --------------------------------------------------------
    # Get conversation memory
    # --------------------------------------------------------

    memory_context = await get_memory_context(
        app_context.current_user["sub"]
    )


    # --------------------------------------------------------
    # Execute existing SQL workflow
    #
    # db_pool comes from ApplicationContext.
    # --------------------------------------------------------

    result = await run_sql_workflow(
        question,
        schema,
        memory_context,
        app_context.db_pool
    )


    return result


# ============================================================
# Tool Executor Registry
# ============================================================
#
# This maps a tool name to its Python runtime executor.
#
# This is different from TOOLS above.
#
# TOOLS:
#     Used to identify the actual LangChain tool.
#
# TOOL_EXECUTORS:
#     Used to identify how Python should execute it.
#
# ============================================================

TOOL_EXECUTORS = {
    "sql_tool": execute_sql_tool
}


# ============================================================
# Generic Tool Executor
# ============================================================

async def execute_tool(
    tool_name: str,
    tool_args: dict,
    app_context: ApplicationContext
):

    # --------------------------------------------------------
    # Find the executor for the requested tool
    # --------------------------------------------------------

    executor = TOOL_EXECUTORS.get(tool_name)


    # --------------------------------------------------------
    # Safety check
    # --------------------------------------------------------

    if executor is None:

        raise ValueError(
            f"No executor registered for tool: {tool_name}"
        )


    # --------------------------------------------------------
    # Execute the tool
    #
    # tool_args:
    #     Information generated by the LLM
    #
    # app_context:
    #     Information supplied by the application
    # --------------------------------------------------------

    return await executor(
        tool_args,
        app_context
    )


# ============================================================
# Agent
# ============================================================

async def ask_agent(
    question: str,
    app_context: ApplicationContext
):

    messages = [
        HumanMessage(content=question)
    ]

    while True:

        # ====================================================
        # STEP 1
        # Ask the LLM what to do
        # ====================================================

        response = await llm_with_tools.ainvoke(
            messages
        )

        print("\n========== LLM RESPONSE ==========")
        print("Content:", response.content)
        print("Tool Calls:", response.tool_calls)


        # ====================================================
        # STEP 2
        # No more tools required
        # ====================================================

        if not response.tool_calls:

            print("\n========== FINAL ANSWER ==========")
            print(response.content)

            return response


        # ====================================================
        # STEP 3
        # Store the LLM response
        # ====================================================

        messages.append(response)


        # ====================================================
        # STEP 4
        # Execute requested tools
        # ====================================================

        for tool_call in response.tool_calls:

            tool_name = tool_call["name"]

            tool_args = tool_call["args"]

            tool_call_id = tool_call["id"]


            print("\n========== TOOL CALL ==========")
            print("Tool:", tool_name)
            print("Arguments:", tool_args)


            # ------------------------------------------------
            # Python executes the requested tool
            # ------------------------------------------------

            tool_result = await execute_tool(
                tool_name=tool_name,
                tool_args=tool_args,
                app_context=app_context
            )


            print("\n========== TOOL RESULT ==========")
            print(tool_result)


            # ------------------------------------------------
            # Send the result back to the LLM
            # ------------------------------------------------

            messages.append(
                ToolMessage(
                    content=str(tool_result),
                    tool_call_id=tool_call_id
                )
            )

        # ----------------------------------------------------
        # IMPORTANT:
        #
        # We DO NOT call the LLM here manually.
        #
        # The while loop goes back to STEP 1.
        #
        # The LLM now sees the ToolMessage and decides
        # what to do next.
        # ----------------------------------------------------